### ISSUE TITLE
Beautify existing code

### ISSUE THREAD

**Issue by ja573** [OpenBookPublishers/epublius#11]
Objective: get code into a state where Luca can confidently make changes

* remove shell / awk subprocesses
* make removal of temporary files mandatory
* break 200-line long function in `epublius_wrapper.py` into smaller units, called `process_epub`

**Comment by rupertgatti** [comment]
Objective:  get code into a state where Luca can confidently make changes

**Comment by lb803** [comment]
I think we got there!
I [added MathJax support](https://github.com/OpenBookPublishers/epublius/commit/ccb2c670d809c4bc6c45dd725c09aeec2ba16d76) in a few minutes.
