### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by ja573** [OpenBookPublishers/epublius#13]
It'd be good to audit the current dependencies (e.g. jquery) to see whether we can get rid of some, perhaps extract just the functionality that we need instead of importing the whole library.

Then we could host all dependencies in our CDN

**Comment by lb803** [comment]
OK, all done.

To sum up:

- Reviewed all the dependencies;
- Removed jquery;
- Moved css, js and OBP logo to the CDN.
