### ISSUE TITLE
Review Site Trackers

### ISSUE THREAD

**Issue by lb803** [OpenBookPublishers/epublius#21]
At present, the [page template](https://github.com/OpenBookPublishers/epublius/blob/master/src/assets/template.xhtml) reports both:

- Google Analytics;
- Piwik (Motomo, I understand).

Do we need them both? @ja573

**Comment by lb803** [comment]
Also, do we need to add a disclaimer?

**Comment by ja573** [comment]
Yes, both are needed. A cookie warning would be useful as the reader may not have come through the website (where there is one)

**Comment by lb803** [comment]
Awesome, thanks Javi!
